import type { TranslationKey } from "./i18n";
import type { UiLanguage } from "./languages";

// Complete dictionaries: never expose a language choice backed by English
// spreads or partial overrides. The type checker and placeholder tests gate
// new strings, including dialogs, notices and accessible icon labels.
type Dictionary = Record<TranslationKey, string>;

const ID: Dictionary = {
  sectionInterface: "Antarmuka", sectionLayout: "Tata letak kartu", sectionBrowsing: "Bawaan penelusuran", sectionIcons: "Ikon", sectionCache: "Cache gambar mini",
  iconOriginal: "Ikon folder asli", iconFolder: "Folder", iconFolders: "Beberapa folder", iconArchive: "Arsip", iconBox: "Kotak", iconLibrary: "Perpustakaan", iconBook: "Buku terbuka", iconHeart: "Folder favorit", iconCog: "Pengaturan folder", iconTree: "Pohon folder", iconGrid: "Kisi", iconGallery: "Galeri", iconImages: "Gambar", iconFilm: "Film", iconClapperboard: "Papan klaket", iconPalette: "Palet", iconHome: "Beranda",
  viewTitle: "Galeri visual", gallery: "Galeri visual", rename: "Ubah nama", delete: "Hapus", deleteFailed: "Tidak dapat menghapus. Periksa izin dan coba lagi.", showInFinder: "Tampilkan di Finder", showInSystem: "Tampilkan di pengelola berkas", revealFailed: "Tidak dapat menampilkan item di pengelola berkas.", newNote: "Catatan baru", newFolder: "Folder baru", create: "Buat", createFailed: "Tidak dapat membuat item. Periksa nama, tujuan, dan izin.", untitledNote: "Tanpa judul", untitledFolder: "Folder tanpa nama", fileName: "Nama", extensionKept: "Ekstensi berkas dipertahankan secara otomatis.", invalidName: "Masukkan nama yang valid tanpa pemisah jalur atau karakter khusus.", renameFailed: "Tidak dapat mengubah nama. Periksa nama dan coba lagi.", cancel: "Batal", movedCount: "{count} item dipindahkan ke {folder}.", partialMove: "{count} dari {total} item dipindahkan. Sisanya tidak dipindahkan. Periksa tujuan dan coba lagi.",
  settingTitle: "Judul beranda", settingFolderIcon: "Ikon kartu folder", settingNavigationIcon: "Ikon navigasi kiri", iconName: "{name}", settingTitleDesc: "Judul khusus di beranda galeri. Kosongkan untuk memakai nama bawaan yang diterjemahkan.", lightColors: "Warna sampul mode terang", darkColors: "Warna sampul mode gelap", folderCoverColors: "Warna sampul folder", noteCoverColors: "Warna sampul kartu catatan", gradientDesc: "Gradasi dari kiri atas ke kanan bawah. Mengubah latar sampul, bukan gambarnya.", gradientStart: "Warna kiri atas", gradientEnd: "Warna kanan bawah", cacheLocation: "Lokasi cache (relatif terhadap vault)", cacheDesc: "Hanya menghapus gambar mini Canvas/PDF yang dibuat, bukan berkas asli. Gambar mini yang terlihat dibuat ulang sesuai kebutuhan. Cache tidak valid atau tanpa sumber dibersihkan otomatis.", cacheFailed: "Tidak dapat membersihkan cache. Periksa izin folder.",
  itemCount: "{count} item dalam folder ini", noMatches: "Tidak ada item yang cocok dalam folder ini.", filterAria: "Filter item galeri", sortAria: "Urutkan item galeri", filterAll: "Semua", filterCanvas: "Canvas", filterNotes: "Catatan", filterImages: "Gambar", filterPdf: "PDF", sortModified: "Baru diubah", sortName: "Nama", sortNameAsc: "Nama berkas (A–Z)", sortNameDesc: "Nama berkas (Z–A)", sortModifiedDesc: "Waktu perubahan (terbaru dahulu)", sortModifiedAsc: "Waktu perubahan (terlama dahulu)", sortCreatedDesc: "Waktu pembuatan (terbaru dahulu)", sortCreatedAsc: "Waktu pembuatan (terlama dahulu)", kindFolder: "Folder", kindCanvas: "Canvas", kindNote: "Catatan", kindImage: "Gambar", kindPdf: "PDF",
  settingLanguage: "Bahasa antarmuka", settingLanguageDesc: "Pilih bahasa Visual Gallery.", settingCardWidth: "Lebar kartu", settingCardWidthDesc: "Sesuaikan lebar dan kepadatan kartu.", settingDefaultFilter: "Filter bawaan", settingDefaultFilterDesc: "Diterapkan saat membuka galeri baru.", settingDefaultSort: "Urutan bawaan", settingDefaultSortDesc: "Diterapkan saat membuka galeri baru.", settingMetadata: "Tampilkan informasi tambahan", settingMetadataDesc: "Menampilkan jenis berkas dan tanggal perubahan di bawah judul.", commandOpen: "Buka galeri visual", commandRebuild: "Buat ulang semua gambar mini Canvas", commandClear: "Bersihkan cache gambar mini", commandGenerate: "Buat gambar mini Canvas", thumbnailGenerated: "Gambar mini Canvas dibuat: {width}×{height}", thumbnailCached: "Gambar mini Canvas dari cache: {width}×{height}", thumbnailWarnings: " ({count} peringatan item)", thumbnailFailed: "Gambar mini Canvas gagal: {detail}", noCanvas: "Visual Gallery: tidak ditemukan berkas Canvas.", rebuilding: "Visual Gallery: membuat ulang {count} gambar mini Canvas…", rebuilt: "Visual Gallery: {count} gambar mini Canvas dibuat ulang.", rebuildFailed: "Visual Gallery: {success} berhasil; {failed} gagal. Periksa konsol pengembang.", cacheCleared: "Cache gambar mini Visual Gallery dibersihkan.", dragUnavailable: "Penyeretan berkas tidak tersedia dalam versi Obsidian ini.", invalidTarget: "Folder tidak dapat dipindahkan ke dirinya sendiri atau subfoldernya.", nameConflict: "Tujuan sudah berisi item dengan nama ini. Tidak ada yang dipindahkan.", movedTo: "{name} dipindahkan ke {folder}.", moveFailed: "Tidak dapat memindahkan. Periksa tujuan dan coba lagi.",
};

const VI: Dictionary = {
  sectionInterface: "Giao diện", sectionLayout: "Bố cục thẻ", sectionBrowsing: "Mặc định duyệt", sectionIcons: "Biểu tượng", sectionCache: "Bộ nhớ đệm ảnh thu nhỏ",
  iconOriginal: "Biểu tượng thư mục gốc", iconFolder: "Thư mục", iconFolders: "Nhiều thư mục", iconArchive: "Lưu trữ", iconBox: "Hộp", iconLibrary: "Thư viện", iconBook: "Sách mở", iconHeart: "Thư mục yêu thích", iconCog: "Cài đặt thư mục", iconTree: "Cây thư mục", iconGrid: "Lưới", iconGallery: "Thư viện ảnh", iconImages: "Hình ảnh", iconFilm: "Phim", iconClapperboard: "Bảng clapper", iconPalette: "Bảng màu", iconHome: "Trang chủ",
  viewTitle: "Thư viện trực quan", gallery: "Thư viện trực quan", rename: "Đổi tên", delete: "Xóa", deleteFailed: "Không thể xóa. Kiểm tra quyền truy cập rồi thử lại.", showInFinder: "Hiển thị trong Finder", showInSystem: "Hiển thị trong trình quản lý tệp", revealFailed: "Không thể hiển thị mục này trong trình quản lý tệp.", newNote: "Ghi chú mới", newFolder: "Thư mục mới", create: "Tạo", createFailed: "Không thể tạo. Kiểm tra tên, đích đến và quyền truy cập.", untitledNote: "Không có tiêu đề", untitledFolder: "Thư mục chưa đặt tên", fileName: "Tên", extensionKept: "Phần mở rộng của tệp được tự động giữ nguyên.", invalidName: "Nhập tên hợp lệ không chứa dấu phân cách đường dẫn hoặc ký tự đặc biệt.", renameFailed: "Không thể đổi tên. Kiểm tra tên rồi thử lại.", cancel: "Hủy", movedCount: "Đã chuyển {count} mục vào {folder}.", partialMove: "Đã chuyển {count} trong {total} mục. Các mục còn lại chưa được chuyển. Kiểm tra đích đến rồi thử lại.",
  settingTitle: "Tiêu đề trang chủ", settingFolderIcon: "Biểu tượng thẻ thư mục", settingNavigationIcon: "Biểu tượng điều hướng bên trái", iconName: "{name}", settingTitleDesc: "Tiêu đề tùy chỉnh trên trang chủ. Để trống để dùng tên mặc định đã dịch.", lightColors: "Màu bìa ở chế độ sáng", darkColors: "Màu bìa ở chế độ tối", folderCoverColors: "Màu bìa thư mục", noteCoverColors: "Màu bìa thẻ ghi chú", gradientDesc: "Chuyển màu từ góc trên trái đến góc dưới phải. Chỉ đổi nền bìa, không đổi hình ảnh.", gradientStart: "Màu góc trên trái", gradientEnd: "Màu góc dưới phải", cacheLocation: "Vị trí bộ nhớ đệm (tương đối với kho)", cacheDesc: "Chỉ xóa ảnh thu nhỏ Canvas/PDF đã tạo, không xóa bản gốc. Ảnh đang hiển thị được tạo lại khi cần. Bộ nhớ đệm không hợp lệ hoặc không còn nguồn được tự động dọn dẹp.", cacheFailed: "Không thể xóa bộ nhớ đệm. Kiểm tra quyền truy cập thư mục.",
  itemCount: "{count} mục trong thư mục này", noMatches: "Không có mục phù hợp trong thư mục này.", filterAria: "Lọc thư viện", sortAria: "Sắp xếp thư viện", filterAll: "Tất cả", filterCanvas: "Canvas", filterNotes: "Ghi chú", filterImages: "Hình ảnh", filterPdf: "PDF", sortModified: "Sửa đổi gần đây", sortName: "Tên", sortNameAsc: "Tên tệp (A–Z)", sortNameDesc: "Tên tệp (Z–A)", sortModifiedDesc: "Sửa đổi (mới đến cũ)", sortModifiedAsc: "Sửa đổi (cũ đến mới)", sortCreatedDesc: "Tạo (mới đến cũ)", sortCreatedAsc: "Tạo (cũ đến mới)", kindFolder: "Thư mục", kindCanvas: "Canvas", kindNote: "Ghi chú", kindImage: "Hình ảnh", kindPdf: "PDF",
  settingLanguage: "Ngôn ngữ giao diện", settingLanguageDesc: "Chọn ngôn ngữ cho Visual Gallery.", settingCardWidth: "Chiều rộng thẻ", settingCardWidthDesc: "Điều chỉnh chiều rộng và mật độ thẻ.", settingDefaultFilter: "Bộ lọc mặc định", settingDefaultFilterDesc: "Áp dụng khi mở thư viện mới.", settingDefaultSort: "Sắp xếp mặc định", settingDefaultSortDesc: "Áp dụng khi mở thư viện mới.", settingMetadata: "Hiển thị thông tin phụ", settingMetadataDesc: "Hiển thị loại tệp và ngày sửa đổi dưới tiêu đề.", commandOpen: "Mở thư viện trực quan", commandRebuild: "Tạo lại tất cả ảnh thu nhỏ Canvas", commandClear: "Xóa bộ nhớ đệm ảnh thu nhỏ", commandGenerate: "Tạo ảnh thu nhỏ Canvas", thumbnailGenerated: "Đã tạo ảnh thu nhỏ Canvas: {width}×{height}", thumbnailCached: "Đã dùng ảnh thu nhỏ Canvas từ bộ nhớ đệm: {width}×{height}", thumbnailWarnings: " ({count} cảnh báo mục)", thumbnailFailed: "Tạo ảnh thu nhỏ Canvas thất bại: {detail}", noCanvas: "Visual Gallery: không tìm thấy tệp Canvas.", rebuilding: "Visual Gallery: đang tạo lại {count} ảnh thu nhỏ Canvas…", rebuilt: "Visual Gallery: đã tạo lại {count} ảnh thu nhỏ Canvas.", rebuildFailed: "Visual Gallery: {success} thành công; {failed} thất bại. Kiểm tra bảng điều khiển dành cho nhà phát triển.", cacheCleared: "Đã xóa bộ nhớ đệm ảnh thu nhỏ Visual Gallery.", dragUnavailable: "Không thể kéo tệp trong phiên bản Obsidian này.", invalidTarget: "Không thể chuyển thư mục vào chính nó hoặc thư mục con của nó.", nameConflict: "Đích đến đã có mục cùng tên. Không có mục nào được chuyển.", movedTo: "Đã chuyển {name} vào {folder}.", moveFailed: "Không thể chuyển. Kiểm tra đích đến rồi thử lại.",
};

const TH: Dictionary = {
  sectionInterface: "ส่วนติดต่อผู้ใช้", sectionLayout: "การจัดวางการ์ด", sectionBrowsing: "ค่าเริ่มต้นการเรียกดู", sectionIcons: "ไอคอน", sectionCache: "แคชภาพย่อ",
  iconOriginal: "ไอคอนโฟลเดอร์เดิม", iconFolder: "โฟลเดอร์", iconFolders: "หลายโฟลเดอร์", iconArchive: "กล่องเก็บถาวร", iconBox: "กล่อง", iconLibrary: "ห้องสมุด", iconBook: "หนังสือเปิด", iconHeart: "โฟลเดอร์โปรด", iconCog: "การตั้งค่าโฟลเดอร์", iconTree: "ผังโฟลเดอร์", iconGrid: "ตาราง", iconGallery: "แกลเลอรี", iconImages: "รูปภาพ", iconFilm: "ฟิล์ม", iconClapperboard: "กระดานชนวน", iconPalette: "จานสี", iconHome: "หน้าหลัก",
  viewTitle: "แกลเลอรีภาพ", gallery: "แกลเลอรีภาพ", rename: "เปลี่ยนชื่อ", delete: "ลบ", deleteFailed: "ลบไม่สำเร็จ โปรดตรวจสอบสิทธิ์แล้วลองอีกครั้ง", showInFinder: "แสดงใน Finder", showInSystem: "แสดงในตัวจัดการไฟล์", revealFailed: "ไม่สามารถแสดงรายการนี้ในตัวจัดการไฟล์ได้", newNote: "บันทึกใหม่", newFolder: "โฟลเดอร์ใหม่", create: "สร้าง", createFailed: "สร้างไม่สำเร็จ โปรดตรวจสอบชื่อ ปลายทาง และสิทธิ์", untitledNote: "ไม่มีชื่อ", untitledFolder: "โฟลเดอร์ไม่มีชื่อ", fileName: "ชื่อ", extensionKept: "นามสกุลไฟล์จะคงเดิมโดยอัตโนมัติ", invalidName: "โปรดระบุชื่อที่ถูกต้องโดยไม่มีตัวคั่นเส้นทางหรืออักขระพิเศษ", renameFailed: "เปลี่ยนชื่อไม่สำเร็จ โปรดตรวจสอบชื่อแล้วลองอีกครั้ง", cancel: "ยกเลิก", movedCount: "ย้าย {count} รายการไปยัง {folder} แล้ว", partialMove: "ย้ายแล้ว {count} จาก {total} รายการ รายการที่เหลือไม่ได้ถูกย้าย โปรดตรวจสอบปลายทางแล้วลองอีกครั้ง",
  settingTitle: "หัวข้อหน้าหลัก", settingFolderIcon: "ไอคอนการ์ดโฟลเดอร์", settingNavigationIcon: "ไอคอนแถบนำทางด้านซ้าย", iconName: "{name}", settingTitleDesc: "กำหนดหัวข้อหน้าหลักของแกลเลอรี เว้นว่างเพื่อใช้ชื่อเริ่มต้นตามภาษาที่เลือก", lightColors: "สีปกในโหมดสว่าง", darkColors: "สีปกในโหมดมืด", folderCoverColors: "สีปกโฟลเดอร์", noteCoverColors: "สีปกการ์ดบันทึก", gradientDesc: "ไล่สีจากมุมซ้ายบนไปมุมขวาล่าง เปลี่ยนเฉพาะพื้นหลังปก ไม่เปลี่ยนรูปภาพ", gradientStart: "สีมุมซ้ายบน", gradientEnd: "สีมุมขวาล่าง", cacheLocation: "ตำแหน่งแคช (เทียบกับคลัง)", cacheDesc: "ลบเฉพาะภาพย่อ Canvas/PDF ที่สร้างขึ้น ไม่ลบต้นฉบับ ภาพย่อที่แสดงจะสร้างใหม่เมื่อจำเป็น แคชที่ใช้ไม่ได้หรือไม่มีแหล่งที่มาจะถูกล้างโดยอัตโนมัติ", cacheFailed: "ล้างแคชไม่สำเร็จ โปรดตรวจสอบสิทธิ์ของโฟลเดอร์",
  itemCount: "{count} รายการในโฟลเดอร์นี้", noMatches: "ไม่มีรายการที่ตรงกันในโฟลเดอร์นี้", filterAria: "กรองรายการในแกลเลอรี", sortAria: "เรียงรายการในแกลเลอรี", filterAll: "ทั้งหมด", filterCanvas: "Canvas", filterNotes: "บันทึก", filterImages: "รูปภาพ", filterPdf: "PDF", sortModified: "แก้ไขล่าสุด", sortName: "ชื่อ", sortNameAsc: "ชื่อไฟล์ (A–Z)", sortNameDesc: "ชื่อไฟล์ (Z–A)", sortModifiedDesc: "เวลาแก้ไข (ใหม่ไปเก่า)", sortModifiedAsc: "เวลาแก้ไข (เก่าไปใหม่)", sortCreatedDesc: "เวลาสร้าง (ใหม่ไปเก่า)", sortCreatedAsc: "เวลาสร้าง (เก่าไปใหม่)", kindFolder: "โฟลเดอร์", kindCanvas: "Canvas", kindNote: "บันทึก", kindImage: "รูปภาพ", kindPdf: "PDF",
  settingLanguage: "ภาษาของส่วนติดต่อผู้ใช้", settingLanguageDesc: "เลือกภาษาที่ใช้ใน Visual Gallery", settingCardWidth: "ความกว้างการ์ด", settingCardWidthDesc: "ปรับความกว้างและความหนาแน่นของการ์ด", settingDefaultFilter: "ตัวกรองเริ่มต้น", settingDefaultFilterDesc: "ใช้เมื่อเปิดแกลเลอรีใหม่", settingDefaultSort: "การเรียงเริ่มต้น", settingDefaultSortDesc: "ใช้เมื่อเปิดแกลเลอรีใหม่", settingMetadata: "แสดงข้อมูลเพิ่มเติม", settingMetadataDesc: "แสดงประเภทไฟล์และวันที่แก้ไขใต้ชื่อการ์ด", commandOpen: "เปิดแกลเลอรีภาพ", commandRebuild: "สร้างภาพย่อ Canvas ทั้งหมดใหม่", commandClear: "ล้างแคชภาพย่อ", commandGenerate: "สร้างภาพย่อ Canvas", thumbnailGenerated: "สร้างภาพย่อ Canvas แล้ว: {width}×{height}", thumbnailCached: "ใช้ภาพย่อ Canvas จากแคช: {width}×{height}", thumbnailWarnings: " (คำเตือนรายการ {count} รายการ)", thumbnailFailed: "สร้างภาพย่อ Canvas ไม่สำเร็จ: {detail}", noCanvas: "Visual Gallery: ไม่พบไฟล์ Canvas", rebuilding: "Visual Gallery: กำลังสร้างภาพย่อ Canvas {count} ภาพใหม่…", rebuilt: "Visual Gallery: สร้างภาพย่อ Canvas {count} ภาพใหม่แล้ว", rebuildFailed: "Visual Gallery: สร้างสำเร็จ {success} ภาพ ล้มเหลว {failed} ภาพ โปรดตรวจสอบคอนโซลนักพัฒนา", cacheCleared: "ล้างแคชภาพย่อ Visual Gallery แล้ว", dragUnavailable: "Obsidian เวอร์ชันนี้ไม่รองรับการลากไฟล์", invalidTarget: "ไม่สามารถย้ายโฟลเดอร์ไปยังตัวเองหรือโฟลเดอร์ย่อยของตัวเองได้", nameConflict: "ปลายทางมีรายการชื่อนี้อยู่แล้ว ไม่มีรายการใดถูกย้าย", movedTo: "ย้าย {name} ไปยัง {folder} แล้ว", moveFailed: "ย้ายไม่สำเร็จ โปรดตรวจสอบปลายทางแล้วลองอีกครั้ง",
};

const NL: Dictionary = {
  sectionInterface: "Interface", sectionLayout: "Kaartindeling", sectionBrowsing: "Standaardweergave", sectionIcons: "Pictogrammen", sectionCache: "Miniaturencache",
  iconOriginal: "Oorspronkelijk mappictogram", iconFolder: "Map", iconFolders: "Mappen", iconArchive: "Archief", iconBox: "Doos", iconLibrary: "Bibliotheek", iconBook: "Open boek", iconHeart: "Favoriete map", iconCog: "Mapinstellingen", iconTree: "Mappenstructuur", iconGrid: "Raster", iconGallery: "Galerij", iconImages: "Afbeeldingen", iconFilm: "Film", iconClapperboard: "Filmklapper", iconPalette: "Palet", iconHome: "Startpagina",
  viewTitle: "Visuele galerij", gallery: "Visuele galerij", rename: "Naam wijzigen", delete: "Verwijderen", deleteFailed: "Verwijderen mislukt. Controleer de toegangsrechten en probeer opnieuw.", showInFinder: "Toon in Finder", showInSystem: "Toon in bestandsbeheer", revealFailed: "Dit item kon niet in bestandsbeheer worden getoond.", newNote: "Nieuwe notitie", newFolder: "Nieuwe map", create: "Aanmaken", createFailed: "Aanmaken mislukt. Controleer de naam, bestemming en toegangsrechten.", untitledNote: "Naamloos", untitledFolder: "Naamloze map", fileName: "Naam", extensionKept: "De bestandsextensie blijft automatisch behouden.", invalidName: "Voer een geldige naam in zonder padscheidingstekens of speciale tekens.", renameFailed: "Naam wijzigen mislukt. Controleer de naam en probeer opnieuw.", cancel: "Annuleren", movedCount: "{count} items verplaatst naar {folder}.", partialMove: "{count} van {total} items verplaatst. De overige zijn niet verplaatst. Controleer de bestemming en probeer opnieuw.",
  settingTitle: "Kop van de startpagina", settingFolderIcon: "Pictogram voor mapkaarten", settingNavigationIcon: "Pictogram voor linkernavigatie", iconName: "{name}", settingTitleDesc: "Eigen kop op de startpagina. Laat leeg voor de vertaalde standaardnaam.", lightColors: "Omslagkleuren in lichte modus", darkColors: "Omslagkleuren in donkere modus", folderCoverColors: "Omslagkleuren voor mappen", noteCoverColors: "Omslagkleuren voor notities", gradientDesc: "Kleurverloop van linksboven naar rechtsonder. Wijzigt de achtergrond, niet de afbeelding.", gradientStart: "Kleur linksboven", gradientEnd: "Kleur rechtsonder", cacheLocation: "Cachelocatie (relatief aan de kluis)", cacheDesc: "Verwijdert alleen gegenereerde Canvas-/PDF-miniaturen, geen originelen. Zichtbare miniaturen worden zo nodig opnieuw gemaakt. Ongeldige en verweesde cache-items worden automatisch opgeruimd.", cacheFailed: "Cache wissen mislukt. Controleer de maprechten.",
  itemCount: "{count} items in deze map", noMatches: "Geen overeenkomende items in deze map.", filterAria: "Galerij filteren", sortAria: "Galerij sorteren", filterAll: "Alle", filterCanvas: "Canvas", filterNotes: "Notities", filterImages: "Afbeeldingen", filterPdf: "PDF", sortModified: "Onlangs gewijzigd", sortName: "Naam", sortNameAsc: "Bestandsnaam (A–Z)", sortNameDesc: "Bestandsnaam (Z–A)", sortModifiedDesc: "Wijziging (nieuw naar oud)", sortModifiedAsc: "Wijziging (oud naar nieuw)", sortCreatedDesc: "Aanmaak (nieuw naar oud)", sortCreatedAsc: "Aanmaak (oud naar nieuw)", kindFolder: "Map", kindCanvas: "Canvas", kindNote: "Notitie", kindImage: "Afbeelding", kindPdf: "PDF",
  settingLanguage: "Interfacetaal", settingLanguageDesc: "Kies de taal van Visual Gallery.", settingCardWidth: "Kaartbreedte", settingCardWidthDesc: "Pas de breedte en dichtheid van kaarten aan.", settingDefaultFilter: "Standaardfilter", settingDefaultFilterDesc: "Toegepast bij het openen van een nieuwe galerij.", settingDefaultSort: "Standaardsortering", settingDefaultSortDesc: "Toegepast bij het openen van een nieuwe galerij.", settingMetadata: "Extra informatie tonen", settingMetadataDesc: "Toont het bestandstype en de wijzigingsdatum onder de titel.", commandOpen: "Visuele galerij openen", commandRebuild: "Alle Canvas-miniaturen opnieuw maken", commandClear: "Miniaturencache wissen", commandGenerate: "Canvas-miniatuur maken", thumbnailGenerated: "Canvas-miniatuur gemaakt: {width}×{height}", thumbnailCached: "Canvas-miniatuur uit cache: {width}×{height}", thumbnailWarnings: " ({count} itemwaarschuwingen)", thumbnailFailed: "Canvas-miniatuur mislukt: {detail}", noCanvas: "Visual Gallery: geen Canvas-bestanden gevonden.", rebuilding: "Visual Gallery: {count} Canvas-miniaturen opnieuw maken…", rebuilt: "Visual Gallery: {count} Canvas-miniaturen opnieuw gemaakt.", rebuildFailed: "Visual Gallery: {success} gemaakt; {failed} mislukt. Bekijk de ontwikkelaarsconsole.", cacheCleared: "Miniaturencache van Visual Gallery gewist.", dragUnavailable: "Bestanden slepen is niet beschikbaar in deze Obsidian-versie.", invalidTarget: "Een map kan niet naar zichzelf of zijn submappen worden verplaatst.", nameConflict: "De bestemming bevat al een item met deze naam. Er is niets verplaatst.", movedTo: "{name} verplaatst naar {folder}.", moveFailed: "Verplaatsen mislukt. Controleer de bestemming en probeer opnieuw.",
};

const PL: Dictionary = {
  sectionInterface: "Interfejs", sectionLayout: "Układ kart", sectionBrowsing: "Domyślne przeglądanie", sectionIcons: "Ikony", sectionCache: "Pamięć podręczna miniatur",
  iconOriginal: "Oryginalna ikona folderu", iconFolder: "Folder", iconFolders: "Foldery", iconArchive: "Archiwum", iconBox: "Pudełko", iconLibrary: "Biblioteka", iconBook: "Otwarta książka", iconHeart: "Ulubiony folder", iconCog: "Ustawienia folderu", iconTree: "Drzewo folderów", iconGrid: "Siatka", iconGallery: "Galeria", iconImages: "Obrazy", iconFilm: "Film", iconClapperboard: "Klaps filmowy", iconPalette: "Paleta", iconHome: "Strona główna",
  viewTitle: "Galeria wizualna", gallery: "Galeria wizualna", rename: "Zmień nazwę", delete: "Usuń", deleteFailed: "Nie można usunąć. Sprawdź uprawnienia i spróbuj ponownie.", showInFinder: "Pokaż w Finderze", showInSystem: "Pokaż w menedżerze plików", revealFailed: "Nie można pokazać elementu w menedżerze plików.", newNote: "Nowa notatka", newFolder: "Nowy folder", create: "Utwórz", createFailed: "Nie można utworzyć. Sprawdź nazwę, miejsce docelowe i uprawnienia.", untitledNote: "Bez tytułu", untitledFolder: "Folder bez nazwy", fileName: "Nazwa", extensionKept: "Rozszerzenie pliku jest zachowywane automatycznie.", invalidName: "Wpisz prawidłową nazwę bez separatorów ścieżki i znaków specjalnych.", renameFailed: "Nie można zmienić nazwy. Sprawdź nazwę i spróbuj ponownie.", cancel: "Anuluj", movedCount: "Przeniesiono {count} elementów do {folder}.", partialMove: "Przeniesiono {count} z {total} elementów. Pozostałe nie zostały przeniesione. Sprawdź miejsce docelowe i spróbuj ponownie.",
  settingTitle: "Nagłówek strony głównej", settingFolderIcon: "Ikona karty folderu", settingNavigationIcon: "Ikona lewej nawigacji", iconName: "{name}", settingTitleDesc: "Własny nagłówek strony głównej. Pozostaw puste, aby użyć przetłumaczonej nazwy domyślnej.", lightColors: "Kolory okładki w jasnym motywie", darkColors: "Kolory okładki w ciemnym motywie", folderCoverColors: "Kolory okładek folderów", noteCoverColors: "Kolory okładek notatek", gradientDesc: "Gradient od lewego górnego do prawego dolnego rogu. Zmienia tło okładki, nie obraz.", gradientStart: "Kolor lewego górnego rogu", gradientEnd: "Kolor prawego dolnego rogu", cacheLocation: "Położenie pamięci podręcznej (względem skarbca)", cacheDesc: "Usuwa tylko wygenerowane miniatury Canvas/PDF, nie oryginały. Widoczne miniatury są odtwarzane w razie potrzeby. Nieprawidłowe i osierocone wpisy są automatycznie usuwane.", cacheFailed: "Nie można wyczyścić pamięci podręcznej. Sprawdź uprawnienia folderu.",
  itemCount: "Elementy w tym folderze: {count}", noMatches: "Brak pasujących elementów w tym folderze.", filterAria: "Filtruj galerię", sortAria: "Sortuj galerię", filterAll: "Wszystkie", filterCanvas: "Canvas", filterNotes: "Notatki", filterImages: "Obrazy", filterPdf: "PDF", sortModified: "Ostatnio zmienione", sortName: "Nazwa", sortNameAsc: "Nazwa pliku (A–Z)", sortNameDesc: "Nazwa pliku (Z–A)", sortModifiedDesc: "Modyfikacja (od najnowszych)", sortModifiedAsc: "Modyfikacja (od najstarszych)", sortCreatedDesc: "Utworzenie (od najnowszych)", sortCreatedAsc: "Utworzenie (od najstarszych)", kindFolder: "Folder", kindCanvas: "Canvas", kindNote: "Notatka", kindImage: "Obraz", kindPdf: "PDF",
  settingLanguage: "Język interfejsu", settingLanguageDesc: "Wybierz język Visual Gallery.", settingCardWidth: "Szerokość kart", settingCardWidthDesc: "Dostosuj szerokość i gęstość kart.", settingDefaultFilter: "Domyślny filtr", settingDefaultFilterDesc: "Stosowany przy otwieraniu nowej galerii.", settingDefaultSort: "Domyślne sortowanie", settingDefaultSortDesc: "Stosowane przy otwieraniu nowej galerii.", settingMetadata: "Pokaż dodatkowe informacje", settingMetadataDesc: "Pokazuje typ pliku i datę modyfikacji pod tytułem.", commandOpen: "Otwórz galerię wizualną", commandRebuild: "Odtwórz wszystkie miniatury Canvas", commandClear: "Wyczyść pamięć podręczną miniatur", commandGenerate: "Wygeneruj miniaturę Canvas", thumbnailGenerated: "Wygenerowano miniaturę Canvas: {width}×{height}", thumbnailCached: "Miniatura Canvas z pamięci podręcznej: {width}×{height}", thumbnailWarnings: " (ostrzeżenia o elementach: {count})", thumbnailFailed: "Błąd miniatury Canvas: {detail}", noCanvas: "Visual Gallery: nie znaleziono plików Canvas.", rebuilding: "Visual Gallery: odtwarzanie {count} miniatur Canvas…", rebuilt: "Visual Gallery: odtworzono {count} miniatur Canvas.", rebuildFailed: "Visual Gallery: utworzono {success}; błędy: {failed}. Sprawdź konsolę deweloperską.", cacheCleared: "Wyczyszczono pamięć podręczną miniatur Visual Gallery.", dragUnavailable: "Przeciąganie plików jest niedostępne w tej wersji Obsidian.", invalidTarget: "Nie można przenieść folderu do niego samego ani do jego podfolderów.", nameConflict: "Miejsce docelowe zawiera już element o tej nazwie. Niczego nie przeniesiono.", movedTo: "Przeniesiono {name} do {folder}.", moveFailed: "Nie można przenieść. Sprawdź miejsce docelowe i spróbuj ponownie.",
};

const TR: Dictionary = {
  sectionInterface: "Arayüz", sectionLayout: "Kart düzeni", sectionBrowsing: "Gezinme varsayılanları", sectionIcons: "Simgeler", sectionCache: "Küçük resim önbelleği",
  iconOriginal: "Özgün klasör simgesi", iconFolder: "Klasör", iconFolders: "Klasörler", iconArchive: "Arşiv", iconBox: "Kutu", iconLibrary: "Kitaplık", iconBook: "Açık kitap", iconHeart: "Favori klasör", iconCog: "Klasör ayarları", iconTree: "Klasör ağacı", iconGrid: "Izgara", iconGallery: "Galeri", iconImages: "Görseller", iconFilm: "Film", iconClapperboard: "Klaket", iconPalette: "Palet", iconHome: "Ana sayfa",
  viewTitle: "Görsel galeri", gallery: "Görsel galeri", rename: "Yeniden adlandır", delete: "Sil", deleteFailed: "Silinemedi. İzinleri kontrol edip tekrar deneyin.", showInFinder: "Finder’da göster", showInSystem: "Dosya yöneticisinde göster", revealFailed: "Bu öğe dosya yöneticisinde gösterilemedi.", newNote: "Yeni not", newFolder: "Yeni klasör", create: "Oluştur", createFailed: "Oluşturulamadı. Adı, hedefi ve izinleri kontrol edin.", untitledNote: "Adsız", untitledFolder: "Adsız klasör", fileName: "Ad", extensionKept: "Dosya uzantısı otomatik olarak korunur.", invalidName: "Yol ayırıcıları veya özel karakterler içermeyen geçerli bir ad girin.", renameFailed: "Yeniden adlandırılamadı. Adı kontrol edip tekrar deneyin.", cancel: "İptal", movedCount: "{count} öğe {folder} klasörüne taşındı.", partialMove: "{total} öğeden {count} tanesi taşındı. Kalanlar taşınmadı. Hedefi kontrol edip tekrar deneyin.",
  settingTitle: "Ana sayfa başlığı", settingFolderIcon: "Klasör kartı simgesi", settingNavigationIcon: "Sol gezinme simgesi", iconName: "{name}", settingTitleDesc: "Galeri ana sayfası için özel başlık. Çevrilmiş varsayılan adı kullanmak için boş bırakın.", lightColors: "Açık mod kapak renkleri", darkColors: "Koyu mod kapak renkleri", folderCoverColors: "Klasör kapak renkleri", noteCoverColors: "Not kartı kapak renkleri", gradientDesc: "Sol üstten sağ alta renk geçişi. Kapak arka planını değiştirir, görseli değil.", gradientStart: "Sol üst renk", gradientEnd: "Sağ alt renk", cacheLocation: "Önbellek konumu (kasaya göre)", cacheDesc: "Yalnızca oluşturulan Canvas/PDF küçük resimlerini siler, özgün dosyaları değil. Görünen küçük resimler gerektiğinde yeniden oluşturulur. Geçersiz ve kaynağı olmayan önbellek otomatik temizlenir.", cacheFailed: "Önbellek temizlenemedi. Klasör izinlerini kontrol edin.",
  itemCount: "Bu klasörde {count} öğe", noMatches: "Bu klasörde eşleşen öğe yok.", filterAria: "Galeriyi filtrele", sortAria: "Galeriyi sırala", filterAll: "Tümü", filterCanvas: "Canvas", filterNotes: "Notlar", filterImages: "Görseller", filterPdf: "PDF", sortModified: "Son değiştirilenler", sortName: "Ad", sortNameAsc: "Dosya adı (A–Z)", sortNameDesc: "Dosya adı (Z–A)", sortModifiedDesc: "Değiştirilme (yeniden eskiye)", sortModifiedAsc: "Değiştirilme (eskiden yeniye)", sortCreatedDesc: "Oluşturulma (yeniden eskiye)", sortCreatedAsc: "Oluşturulma (eskiden yeniye)", kindFolder: "Klasör", kindCanvas: "Canvas", kindNote: "Not", kindImage: "Görsel", kindPdf: "PDF",
  settingLanguage: "Arayüz dili", settingLanguageDesc: "Visual Gallery dilini seçin.", settingCardWidth: "Kart genişliği", settingCardWidthDesc: "Kartların genişliğini ve yoğunluğunu ayarlayın.", settingDefaultFilter: "Varsayılan filtre", settingDefaultFilterDesc: "Yeni galeri açıldığında uygulanır.", settingDefaultSort: "Varsayılan sıralama", settingDefaultSortDesc: "Yeni galeri açıldığında uygulanır.", settingMetadata: "Ek bilgileri göster", settingMetadataDesc: "Başlığın altında dosya türünü ve değiştirilme tarihini gösterir.", commandOpen: "Görsel galeriyi aç", commandRebuild: "Tüm Canvas küçük resimlerini yeniden oluştur", commandClear: "Küçük resim önbelleğini temizle", commandGenerate: "Canvas küçük resmi oluştur", thumbnailGenerated: "Canvas küçük resmi oluşturuldu: {width}×{height}", thumbnailCached: "Canvas küçük resmi önbellekten kullanıldı: {width}×{height}", thumbnailWarnings: " ({count} öğe uyarısı)", thumbnailFailed: "Canvas küçük resmi başarısız: {detail}", noCanvas: "Visual Gallery: Canvas dosyası bulunamadı.", rebuilding: "Visual Gallery: {count} Canvas küçük resmi yeniden oluşturuluyor…", rebuilt: "Visual Gallery: {count} Canvas küçük resmi yeniden oluşturuldu.", rebuildFailed: "Visual Gallery: {success} oluşturuldu; {failed} başarısız. Geliştirici konsolunu kontrol edin.", cacheCleared: "Visual Gallery küçük resim önbelleği temizlendi.", dragUnavailable: "Bu Obsidian sürümünde dosya sürükleme kullanılamıyor.", invalidTarget: "Bir klasör kendisine veya alt klasörlerine taşınamaz.", nameConflict: "Hedefte aynı adlı bir öğe var. Hiçbir şey taşınmadı.", movedTo: "{name}, {folder} klasörüne taşındı.", moveFailed: "Taşınamadı. Hedefi kontrol edip tekrar deneyin.",
};

const PT_BR: Dictionary = {
  sectionInterface: "Interface", sectionLayout: "Layout dos cartões", sectionBrowsing: "Padrões de navegação", sectionIcons: "Ícones", sectionCache: "Cache de miniaturas",
  iconOriginal: "Ícone de pasta original", iconFolder: "Pasta", iconFolders: "Pastas", iconArchive: "Arquivo", iconBox: "Caixa", iconLibrary: "Biblioteca", iconBook: "Livro aberto", iconHeart: "Pasta favorita", iconCog: "Configurações de pasta", iconTree: "Árvore de pastas", iconGrid: "Grade", iconGallery: "Galeria", iconImages: "Imagens", iconFilm: "Filme", iconClapperboard: "Claquete", iconPalette: "Paleta", iconHome: "Início",
  viewTitle: "Galeria visual", gallery: "Galeria visual", rename: "Renomear", delete: "Excluir", deleteFailed: "Não foi possível excluir. Verifique as permissões e tente novamente.", showInFinder: "Mostrar no Finder", showInSystem: "Mostrar no gerenciador de arquivos", revealFailed: "Não foi possível mostrar este item no gerenciador de arquivos.", newNote: "Nova nota", newFolder: "Nova pasta", create: "Criar", createFailed: "Não foi possível criar. Verifique o nome, o destino e as permissões.", untitledNote: "Sem título", untitledFolder: "Pasta sem título", fileName: "Nome", extensionKept: "A extensão do arquivo é mantida automaticamente.", invalidName: "Digite um nome válido sem separadores de caminho ou caracteres especiais.", renameFailed: "Não foi possível renomear. Verifique o nome e tente novamente.", cancel: "Cancelar",
  movedCount: "{count} itens movidos para {folder}.", partialMove: "{count} de {total} itens movidos. Os demais não foram movidos. Verifique o destino e tente novamente.", settingTitle: "Título da página inicial", settingFolderIcon: "Ícone dos cartões de pasta", settingNavigationIcon: "Ícone da navegação à esquerda", iconName: "{name}", settingTitleDesc: "Título personalizado da página inicial. Deixe vazio para usar o nome padrão traduzido.", lightColors: "Cores de capa no modo claro", darkColors: "Cores de capa no modo escuro", folderCoverColors: "Cores de capa das pastas", noteCoverColors: "Cores de capa das notas", gradientDesc: "Gradiente do canto superior esquerdo ao inferior direito. Altera o fundo da capa, não a imagem.", gradientStart: "Cor superior esquerda", gradientEnd: "Cor inferior direita",
  cacheLocation: "Local do cache (relativo ao cofre)", cacheDesc: "Remove apenas miniaturas Canvas/PDF geradas, nunca os originais. As visíveis são geradas novamente quando necessário. Entradas inválidas ou órfãs são limpas automaticamente.", cacheFailed: "Não foi possível limpar o cache. Verifique as permissões da pasta.", itemCount: "{count} itens nesta pasta", noMatches: "Nenhum item correspondente nesta pasta.", filterAria: "Filtrar a galeria", sortAria: "Ordenar a galeria", filterAll: "Todos", filterCanvas: "Canvas", filterNotes: "Notas", filterImages: "Imagens", filterPdf: "PDF", sortModified: "Modificados recentemente", sortName: "Nome", sortNameAsc: "Nome do arquivo (A–Z)", sortNameDesc: "Nome do arquivo (Z–A)", sortModifiedDesc: "Modificação (mais recente primeiro)", sortModifiedAsc: "Modificação (mais antigo primeiro)", sortCreatedDesc: "Criação (mais recente primeiro)", sortCreatedAsc: "Criação (mais antigo primeiro)", kindFolder: "Pasta", kindCanvas: "Canvas", kindNote: "Nota", kindImage: "Imagem", kindPdf: "PDF",
  settingLanguage: "Idioma da interface", settingLanguageDesc: "Escolha o idioma do Visual Gallery.", settingCardWidth: "Largura dos cartões", settingCardWidthDesc: "Ajuste a largura e a densidade dos cartões.", settingDefaultFilter: "Filtro padrão", settingDefaultFilterDesc: "Aplicado ao abrir uma nova galeria.", settingDefaultSort: "Ordenação padrão", settingDefaultSortDesc: "Aplicada ao abrir uma nova galeria.", settingMetadata: "Mostrar informações secundárias", settingMetadataDesc: "Mostra o tipo de arquivo e a data de modificação abaixo do título.", commandOpen: "Abrir galeria visual", commandRebuild: "Gerar novamente todas as miniaturas Canvas", commandClear: "Limpar cache de miniaturas", commandGenerate: "Gerar miniatura Canvas", thumbnailGenerated: "Miniatura Canvas gerada: {width}×{height}", thumbnailCached: "Miniatura Canvas reutilizada: {width}×{height}", thumbnailWarnings: " ({count} avisos de itens)", thumbnailFailed: "Falha na miniatura Canvas: {detail}", noCanvas: "Visual Gallery: nenhum arquivo Canvas encontrado.", rebuilding: "Visual Gallery: gerando novamente {count} miniaturas Canvas…", rebuilt: "Visual Gallery: {count} miniaturas Canvas geradas novamente.", rebuildFailed: "Visual Gallery: {success} geradas; {failed} falharam. Consulte o console de desenvolvimento.", cacheCleared: "Cache de miniaturas do Visual Gallery limpo.", dragUnavailable: "O arraste de arquivos não está disponível nesta versão do Obsidian.", invalidTarget: "Uma pasta não pode ser movida para si mesma ou suas subpastas.", nameConflict: "O destino já contém um item com este nome. Nada foi movido.", movedTo: "{name} movido para {folder}.", moveFailed: "Não foi possível mover. Verifique o destino e tente novamente.",
};

const KO: Dictionary = {
  sectionInterface: "인터페이스", sectionLayout: "카드 레이아웃", sectionBrowsing: "탐색 기본값", sectionIcons: "아이콘", sectionCache: "썸네일 캐시",
  iconOriginal: "기존 폴더 아이콘", iconFolder: "폴더", iconFolders: "여러 폴더", iconArchive: "보관함", iconBox: "상자", iconLibrary: "라이브러리", iconBook: "펼친 책", iconHeart: "즐겨찾는 폴더", iconCog: "폴더 설정", iconTree: "폴더 트리", iconGrid: "격자", iconGallery: "갤러리", iconImages: "이미지", iconFilm: "필름", iconClapperboard: "클래퍼보드", iconPalette: "팔레트", iconHome: "홈",
  viewTitle: "비주얼 갤러리", gallery: "비주얼 갤러리", rename: "이름 변경", delete: "삭제", deleteFailed: "삭제하지 못했습니다. 권한을 확인하고 다시 시도하세요.", showInFinder: "Finder에서 보기", showInSystem: "파일 관리자에서 보기", revealFailed: "파일 관리자에서 이 항목을 표시하지 못했습니다.", newNote: "새 노트", newFolder: "새 폴더", create: "만들기", createFailed: "만들지 못했습니다. 이름, 대상 위치와 권한을 확인하세요.", untitledNote: "제목 없음", untitledFolder: "이름 없는 폴더", fileName: "이름", extensionKept: "파일 확장자는 자동으로 유지됩니다.", invalidName: "경로 구분자나 특수 문자가 없는 유효한 이름을 입력하세요.", renameFailed: "이름을 변경하지 못했습니다. 이름을 확인하고 다시 시도하세요.", cancel: "취소", movedCount: "{count}개 항목을 {folder}(으)로 이동했습니다.", partialMove: "{total}개 중 {count}개를 이동했습니다. 나머지는 이동하지 않았습니다. 대상 위치를 확인하고 다시 시도하세요.",
  settingTitle: "홈 제목", settingFolderIcon: "폴더 카드 아이콘", settingNavigationIcon: "왼쪽 탐색 아이콘", iconName: "{name}", settingTitleDesc: "갤러리 홈의 사용자 지정 제목입니다. 비워 두면 현재 언어의 기본 이름을 사용합니다.", lightColors: "라이트 모드 표지 색상", darkColors: "다크 모드 표지 색상", folderCoverColors: "폴더 표지 색상", noteCoverColors: "노트 카드 표지 색상", gradientDesc: "왼쪽 위에서 오른쪽 아래로 이어지는 그라데이션입니다. 표지 배경에만 적용되며 이미지는 변경하지 않습니다.", gradientStart: "왼쪽 위 색상", gradientEnd: "오른쪽 아래 색상", cacheLocation: "캐시 위치 (보관함 기준 상대 경로)", cacheDesc: "생성된 Canvas/PDF 썸네일만 삭제하며 원본은 그대로 유지합니다. 표시 중인 썸네일은 필요할 때 다시 생성합니다. 잘못되거나 연결이 끊긴 캐시는 자동 정리합니다.", cacheFailed: "썸네일 캐시를 지우지 못했습니다. 폴더 권한을 확인하세요.",
  itemCount: "이 폴더에 {count}개 항목", noMatches: "이 폴더에 일치하는 항목이 없습니다.", filterAria: "갤러리 항목 필터링", sortAria: "갤러리 항목 정렬", filterAll: "전체", filterCanvas: "Canvas", filterNotes: "노트", filterImages: "이미지", filterPdf: "PDF", sortModified: "최근 수정", sortName: "이름", sortNameAsc: "파일 이름 (A–Z)", sortNameDesc: "파일 이름 (Z–A)", sortModifiedDesc: "수정 시간 (최신순)", sortModifiedAsc: "수정 시간 (오래된순)", sortCreatedDesc: "생성 시간 (최신순)", sortCreatedAsc: "생성 시간 (오래된순)", kindFolder: "폴더", kindCanvas: "Canvas", kindNote: "노트", kindImage: "이미지", kindPdf: "PDF",
  settingLanguage: "인터페이스 언어", settingLanguageDesc: "Visual Gallery에서 사용할 언어를 선택하세요.", settingCardWidth: "카드 너비", settingCardWidthDesc: "카드의 너비와 표시 밀도를 조절합니다.", settingDefaultFilter: "기본 필터", settingDefaultFilterDesc: "새 갤러리를 열 때 적용합니다.", settingDefaultSort: "기본 정렬", settingDefaultSortDesc: "새 갤러리를 열 때 적용합니다.", settingMetadata: "보조 정보 표시", settingMetadataDesc: "카드 제목 아래에 파일 유형과 수정 날짜를 표시합니다.", commandOpen: "비주얼 갤러리 열기", commandRebuild: "모든 Canvas 썸네일 다시 생성", commandClear: "썸네일 캐시 지우기", commandGenerate: "Canvas 썸네일 생성", thumbnailGenerated: "Canvas 썸네일 생성됨: {width}×{height}", thumbnailCached: "Canvas 썸네일 캐시 사용: {width}×{height}", thumbnailWarnings: " (항목 경고 {count}개)", thumbnailFailed: "Canvas 썸네일 생성 실패: {detail}", noCanvas: "Visual Gallery: Canvas 파일이 없습니다.", rebuilding: "Visual Gallery: Canvas 썸네일 {count}개 다시 생성 중…", rebuilt: "Visual Gallery: Canvas 썸네일 {count}개를 다시 생성했습니다.", rebuildFailed: "Visual Gallery: {success}개 생성, {failed}개 실패. 개발자 콘솔을 확인하세요.", cacheCleared: "Visual Gallery 썸네일 캐시를 지웠습니다.", dragUnavailable: "이 Obsidian 버전에서는 파일을 드래그할 수 없습니다.", invalidTarget: "폴더를 자기 자신이나 하위 폴더로 이동할 수 없습니다.", nameConflict: "대상 위치에 같은 이름의 항목이 있습니다. 아무것도 이동하지 않았습니다.", movedTo: "{name}을(를) {folder}(으)로 이동했습니다.", moveFailed: "이동하지 못했습니다. 대상 위치를 확인하고 다시 시도하세요.",
};

const RU: Dictionary = {
  sectionInterface: "Интерфейс", sectionLayout: "Макет карточек", sectionBrowsing: "Настройки просмотра", sectionIcons: "Значки", sectionCache: "Кэш миниатюр",
  iconOriginal: "Исходный значок папки", iconFolder: "Папка", iconFolders: "Папки", iconArchive: "Архив", iconBox: "Коробка", iconLibrary: "Библиотека", iconBook: "Открытая книга", iconHeart: "Избранная папка", iconCog: "Настройки папки", iconTree: "Дерево папок", iconGrid: "Сетка", iconGallery: "Галерея", iconImages: "Изображения", iconFilm: "Плёнка", iconClapperboard: "Хлопушка", iconPalette: "Палитра", iconHome: "Главная",
  viewTitle: "Визуальная галерея", gallery: "Визуальная галерея", rename: "Переименовать", delete: "Удалить", deleteFailed: "Не удалось удалить. Проверьте права доступа и повторите попытку.", showInFinder: "Показать в Finder", showInSystem: "Показать в файловом менеджере", revealFailed: "Не удалось показать элемент в файловом менеджере.", newNote: "Новая заметка", newFolder: "Новая папка", create: "Создать", createFailed: "Не удалось создать. Проверьте имя, место назначения и права доступа.", untitledNote: "Без названия", untitledFolder: "Папка без названия", fileName: "Имя", extensionKept: "Расширение файла сохраняется автоматически.", invalidName: "Введите допустимое имя без разделителей пути и специальных символов.", renameFailed: "Не удалось переименовать. Проверьте имя и повторите попытку.", cancel: "Отмена", movedCount: "Перемещено {count} элементов в {folder}.", partialMove: "Перемещено {count} из {total} элементов. Остальные не перемещены. Проверьте место назначения и повторите попытку.",
  settingTitle: "Заголовок главной страницы", settingFolderIcon: "Значок карточки папки", settingNavigationIcon: "Значок левой навигации", iconName: "{name}", settingTitleDesc: "Свой заголовок главной страницы галереи. Оставьте пустым для названия по умолчанию на выбранном языке.", lightColors: "Цвета обложек в светлой теме", darkColors: "Цвета обложек в тёмной теме", folderCoverColors: "Цвета обложек папок", noteCoverColors: "Цвета обложек заметок", gradientDesc: "Градиент из левого верхнего угла в правый нижний. Меняет фон обложки, но не изображение.", gradientStart: "Цвет слева сверху", gradientEnd: "Цвет справа снизу", cacheLocation: "Расположение кэша (относительно хранилища)", cacheDesc: "Удаляет только созданные миниатюры Canvas/PDF, не оригиналы. Видимые миниатюры создаются заново по мере необходимости. Недействительные и потерявшие источник записи очищаются автоматически.", cacheFailed: "Не удалось очистить кэш. Проверьте права доступа к папке.",
  itemCount: "Элементов в этой папке: {count}", noMatches: "В этой папке нет подходящих элементов.", filterAria: "Фильтровать галерею", sortAria: "Сортировать галерею", filterAll: "Все", filterCanvas: "Canvas", filterNotes: "Заметки", filterImages: "Изображения", filterPdf: "PDF", sortModified: "Недавно изменённые", sortName: "Имя", sortNameAsc: "Имя файла (А–Я)", sortNameDesc: "Имя файла (Я–А)", sortModifiedDesc: "Изменение (от новых к старым)", sortModifiedAsc: "Изменение (от старых к новым)", sortCreatedDesc: "Создание (от новых к старым)", sortCreatedAsc: "Создание (от старых к новым)", kindFolder: "Папка", kindCanvas: "Canvas", kindNote: "Заметка", kindImage: "Изображение", kindPdf: "PDF",
  settingLanguage: "Язык интерфейса", settingLanguageDesc: "Выберите язык Visual Gallery.", settingCardWidth: "Ширина карточек", settingCardWidthDesc: "Настройте ширину и плотность карточек.", settingDefaultFilter: "Фильтр по умолчанию", settingDefaultFilterDesc: "Применяется при открытии новой галереи.", settingDefaultSort: "Сортировка по умолчанию", settingDefaultSortDesc: "Применяется при открытии новой галереи.", settingMetadata: "Показывать дополнительные сведения", settingMetadataDesc: "Показывает тип файла и дату изменения под заголовком.", commandOpen: "Открыть визуальную галерею", commandRebuild: "Пересоздать все миниатюры Canvas", commandClear: "Очистить кэш миниатюр", commandGenerate: "Создать миниатюру Canvas", thumbnailGenerated: "Миниатюра Canvas создана: {width}×{height}", thumbnailCached: "Миниатюра Canvas из кэша: {width}×{height}", thumbnailWarnings: " (предупреждений об элементах: {count})", thumbnailFailed: "Ошибка миниатюры Canvas: {detail}", noCanvas: "Visual Gallery: файлы Canvas не найдены.", rebuilding: "Visual Gallery: пересоздание миниатюр Canvas: {count}…", rebuilt: "Visual Gallery: пересоздано миниатюр Canvas: {count}.", rebuildFailed: "Visual Gallery: создано {success}; ошибок: {failed}. Проверьте консоль разработчика.", cacheCleared: "Кэш миниатюр Visual Gallery очищен.", dragUnavailable: "Перетаскивание файлов недоступно в этой версии Obsidian.", invalidTarget: "Нельзя переместить папку в саму себя или её подпапки.", nameConflict: "В месте назначения уже есть элемент с таким именем. Ничего не перемещено.", movedTo: "{name} перемещён в {folder}.", moveFailed: "Не удалось переместить. Проверьте место назначения и повторите попытку.",
};

const UK: Dictionary = {
  sectionInterface: "Інтерфейс", sectionLayout: "Макет карток", sectionBrowsing: "Типові параметри перегляду", sectionIcons: "Піктограми", sectionCache: "Кеш мініатюр",
  iconOriginal: "Початкова піктограма теки", iconFolder: "Тека", iconFolders: "Теки", iconArchive: "Архів", iconBox: "Коробка", iconLibrary: "Бібліотека", iconBook: "Відкрита книга", iconHeart: "Улюблена тека", iconCog: "Налаштування теки", iconTree: "Дерево тек", iconGrid: "Сітка", iconGallery: "Галерея", iconImages: "Зображення", iconFilm: "Плівка", iconClapperboard: "Кінохлопавка", iconPalette: "Палітра", iconHome: "Головна",
  viewTitle: "Візуальна галерея", gallery: "Візуальна галерея", rename: "Перейменувати", delete: "Видалити", deleteFailed: "Не вдалося видалити. Перевірте дозволи й повторіть спробу.", showInFinder: "Показати у Finder", showInSystem: "Показати у файловому менеджері", revealFailed: "Не вдалося показати елемент у файловому менеджері.", newNote: "Нова нотатка", newFolder: "Нова тека", create: "Створити", createFailed: "Не вдалося створити. Перевірте назву, місце призначення та дозволи.", untitledNote: "Без назви", untitledFolder: "Тека без назви", fileName: "Назва", extensionKept: "Розширення файлу зберігається автоматично.", invalidName: "Введіть коректну назву без роздільників шляху та спеціальних символів.", renameFailed: "Не вдалося перейменувати. Перевірте назву й повторіть спробу.", cancel: "Скасувати", movedCount: "Переміщено {count} елементів до {folder}.", partialMove: "Переміщено {count} із {total} елементів. Решту не переміщено. Перевірте місце призначення й повторіть спробу.",
  settingTitle: "Заголовок головної сторінки", settingFolderIcon: "Піктограма картки теки", settingNavigationIcon: "Піктограма лівої навігації", iconName: "{name}", settingTitleDesc: "Власний заголовок головної сторінки галереї. Залиште порожнім для типової перекладеної назви.", lightColors: "Кольори обкладинки у світлій темі", darkColors: "Кольори обкладинки у темній темі", folderCoverColors: "Кольори обкладинок тек", noteCoverColors: "Кольори обкладинок нотаток", gradientDesc: "Градієнт з верхнього лівого кута до нижнього правого. Змінює фон, а не зображення.", gradientStart: "Колір угорі ліворуч", gradientEnd: "Колір унизу праворуч", cacheLocation: "Розташування кешу (відносно сховища)", cacheDesc: "Видаляє лише створені мініатюри Canvas/PDF, не оригінали. Видимі мініатюри створюються знову за потреби. Недійсні записи та записи без джерела очищуються автоматично.", cacheFailed: "Не вдалося очистити кеш. Перевірте дозволи теки.", itemCount: "Елементів у цій теці: {count}", noMatches: "У цій теці немає відповідних елементів.", filterAria: "Фільтрувати галерею", sortAria: "Сортувати галерею", filterAll: "Усі", filterCanvas: "Canvas", filterNotes: "Нотатки", filterImages: "Зображення", filterPdf: "PDF",
  sortModified: "Нещодавно змінені", sortName: "Назва", sortNameAsc: "Назва файлу (А–Я)", sortNameDesc: "Назва файлу (Я–А)", sortModifiedDesc: "Зміна (від нових до старих)", sortModifiedAsc: "Зміна (від старих до нових)", sortCreatedDesc: "Створення (від нових до старих)", sortCreatedAsc: "Створення (від старих до нових)", kindFolder: "Тека", kindCanvas: "Canvas", kindNote: "Нотатка", kindImage: "Зображення", kindPdf: "PDF", settingLanguage: "Мова інтерфейсу", settingLanguageDesc: "Виберіть мову Visual Gallery.", settingCardWidth: "Ширина карток", settingCardWidthDesc: "Налаштуйте ширину та щільність карток.", settingDefaultFilter: "Типовий фільтр", settingDefaultFilterDesc: "Застосовується під час відкриття нової галереї.", settingDefaultSort: "Типове сортування", settingDefaultSortDesc: "Застосовується під час відкриття нової галереї.", settingMetadata: "Показувати додаткові відомості", settingMetadataDesc: "Показує тип файлу й дату зміни під заголовком.", commandOpen: "Відкрити візуальну галерею", commandRebuild: "Повторно створити всі мініатюри Canvas", commandClear: "Очистити кеш мініатюр", commandGenerate: "Створити мініатюру Canvas", thumbnailGenerated: "Мініатюру Canvas створено: {width}×{height}", thumbnailCached: "Мініатюра Canvas з кешу: {width}×{height}", thumbnailWarnings: " (попереджень про елементи: {count})", thumbnailFailed: "Помилка мініатюри Canvas: {detail}", noCanvas: "Visual Gallery: файлів Canvas не знайдено.", rebuilding: "Visual Gallery: повторне створення {count} мініатюр Canvas…", rebuilt: "Visual Gallery: повторно створено {count} мініатюр Canvas.", rebuildFailed: "Visual Gallery: створено {success}; помилок: {failed}. Перевірте консоль розробника.", cacheCleared: "Кеш мініатюр Visual Gallery очищено.", dragUnavailable: "Перетягування файлів недоступне в цій версії Obsidian.", invalidTarget: "Не можна перемістити теку в себе або свої підтеки.", nameConflict: "У місці призначення вже є елемент із такою назвою. Нічого не переміщено.", movedTo: "{name} переміщено до {folder}.", moveFailed: "Не вдалося перемістити. Перевірте місце призначення й повторіть спробу.",
};

const DE: Dictionary = {
  sectionInterface: "Oberfläche", sectionLayout: "Kartenlayout", sectionBrowsing: "Standardansicht", sectionIcons: "Symbole", sectionCache: "Vorschaubild-Cache",
  iconOriginal: "Ursprüngliches Ordnersymbol", iconFolder: "Ordner", iconFolders: "Mehrere Ordner", iconArchive: "Archiv", iconBox: "Box", iconLibrary: "Bibliothek", iconBook: "Offenes Buch", iconHeart: "Favoritenordner", iconCog: "Ordnereinstellungen", iconTree: "Ordnerbaum", iconGrid: "Raster", iconGallery: "Galerie", iconImages: "Bilder", iconFilm: "Film", iconClapperboard: "Filmklappe", iconPalette: "Palette", iconHome: "Startseite",
  viewTitle: "Visuelle Galerie", gallery: "Visuelle Galerie", rename: "Umbenennen", delete: "Löschen", deleteFailed: "Löschen fehlgeschlagen. Prüfe die Zugriffsrechte und versuche es erneut.",
  showInFinder: "Im Finder anzeigen", showInSystem: "Im Dateimanager anzeigen", revealFailed: "Dieses Element konnte nicht im Dateimanager angezeigt werden.",
  newNote: "Neue Notiz", newFolder: "Neuer Ordner", create: "Erstellen", createFailed: "Erstellen fehlgeschlagen. Prüfe Name, Ziel und Zugriffsrechte.", untitledNote: "Unbenannt", untitledFolder: "Unbenannter Ordner",
  fileName: "Name", extensionKept: "Die Dateiendung bleibt automatisch erhalten.", invalidName: "Gib einen gültigen Namen ohne Pfadtrennzeichen oder Sonderzeichen ein.", renameFailed: "Umbenennen fehlgeschlagen. Prüfe den Namen und versuche es erneut.", cancel: "Abbrechen",
  movedCount: "{count} Elemente nach {folder} verschoben.", partialMove: "{count} von {total} Elementen verschoben. Die übrigen wurden nicht verschoben. Prüfe das Ziel und versuche es erneut.",
  settingTitle: "Überschrift der Startseite", settingFolderIcon: "Symbol der Ordnerkarten", settingNavigationIcon: "Symbol der linken Navigation", iconName: "{name}", settingTitleDesc: "Eigene Überschrift auf der Galerie-Startseite. Leer lassen für den übersetzten Standardnamen.",
  lightColors: "Coverfarben im hellen Modus", darkColors: "Coverfarben im dunklen Modus", folderCoverColors: "Ordner-Coverfarben", noteCoverColors: "Notiz-Coverfarben", gradientDesc: "Verlauf von links oben nach rechts unten. Ändert den Coverhintergrund, nicht das Bild.", gradientStart: "Farbe links oben", gradientEnd: "Farbe rechts unten",
  cacheLocation: "Cache-Speicherort (relativ zum Vault)", cacheDesc: "Löscht nur erzeugte Canvas-/PDF-Vorschaubilder, keine Originale. Sichtbare Vorschauen werden bei Bedarf neu erzeugt. Ungültige und verwaiste Einträge werden automatisch entfernt.", cacheFailed: "Cache konnte nicht geleert werden. Prüfe die Ordnerrechte.",
  itemCount: "{count} Elemente in diesem Ordner", noMatches: "Keine passenden Elemente in diesem Ordner.", filterAria: "Galerie filtern", sortAria: "Galerie sortieren", filterAll: "Alle", filterCanvas: "Canvas", filterNotes: "Notizen", filterImages: "Bilder", filterPdf: "PDF",
  sortModified: "Zuletzt geändert", sortName: "Name", sortNameAsc: "Dateiname (A–Z)", sortNameDesc: "Dateiname (Z–A)", sortModifiedDesc: "Änderungsdatum (neu nach alt)", sortModifiedAsc: "Änderungsdatum (alt nach neu)", sortCreatedDesc: "Erstellungsdatum (neu nach alt)", sortCreatedAsc: "Erstellungsdatum (alt nach neu)",
  kindFolder: "Ordner", kindCanvas: "Canvas", kindNote: "Notiz", kindImage: "Bild", kindPdf: "PDF",
  settingLanguage: "Sprache der Oberfläche", settingLanguageDesc: "Wähle die Sprache von Visual Gallery.", settingCardWidth: "Kartenbreite", settingCardWidthDesc: "Passe Breite und Dichte der Karten an.", settingDefaultFilter: "Standardfilter", settingDefaultFilterDesc: "Wird beim Öffnen einer neuen Galerie angewendet.", settingDefaultSort: "Standardsortierung", settingDefaultSortDesc: "Wird beim Öffnen einer neuen Galerie angewendet.", settingMetadata: "Zusatzinformationen anzeigen", settingMetadataDesc: "Zeigt Dateityp und Änderungsdatum unter dem Kartentitel.",
  commandOpen: "Visuelle Galerie öffnen", commandRebuild: "Alle Canvas-Vorschaubilder neu erzeugen", commandClear: "Vorschaubild-Cache leeren", commandGenerate: "Canvas-Vorschaubild erzeugen",
  thumbnailGenerated: "Canvas-Vorschaubild erzeugt: {width}×{height}", thumbnailCached: "Canvas-Vorschaubild aus dem Cache: {width}×{height}", thumbnailWarnings: " ({count} Elementwarnungen)", thumbnailFailed: "Canvas-Vorschaubild fehlgeschlagen: {detail}", noCanvas: "Visual Gallery: keine Canvas-Dateien gefunden.", rebuilding: "Visual Gallery: {count} Canvas-Vorschaubilder werden neu erzeugt…", rebuilt: "Visual Gallery: {count} Canvas-Vorschaubilder neu erzeugt.", rebuildFailed: "Visual Gallery: {success} erzeugt; {failed} fehlgeschlagen. Prüfe die Entwicklerkonsole.", cacheCleared: "Vorschaubild-Cache von Visual Gallery geleert.",
  dragUnavailable: "Dateien können in dieser Obsidian-Version nicht gezogen werden.", invalidTarget: "Ein Ordner kann nicht in sich selbst oder seine Unterordner verschoben werden.", nameConflict: "Das Ziel enthält bereits ein Element mit diesem Namen. Nichts wurde verschoben.", movedTo: "{name} nach {folder} verschoben.", moveFailed: "Verschieben fehlgeschlagen. Prüfe das Ziel und versuche es erneut.",
};

const ES: Dictionary = {
  sectionInterface: "Interfaz", sectionLayout: "Diseño de tarjetas", sectionBrowsing: "Navegación predeterminada", sectionIcons: "Iconos", sectionCache: "Caché de miniaturas",
  iconOriginal: "Icono de carpeta original", iconFolder: "Carpeta", iconFolders: "Carpetas", iconArchive: "Archivo", iconBox: "Caja", iconLibrary: "Biblioteca", iconBook: "Libro abierto", iconHeart: "Carpeta favorita", iconCog: "Ajustes de carpeta", iconTree: "Árbol de carpetas", iconGrid: "Cuadrícula", iconGallery: "Galería", iconImages: "Imágenes", iconFilm: "Película", iconClapperboard: "Claqueta", iconPalette: "Paleta", iconHome: "Inicio",
  viewTitle: "Galería visual", gallery: "Galería visual", rename: "Renombrar", delete: "Eliminar", deleteFailed: "No se pudo eliminar. Comprueba los permisos e inténtalo de nuevo.", showInFinder: "Mostrar en Finder", showInSystem: "Mostrar en el gestor de archivos", revealFailed: "No se pudo mostrar este elemento en el gestor de archivos.",
  newNote: "Nueva nota", newFolder: "Nueva carpeta", create: "Crear", createFailed: "No se pudo crear. Comprueba el nombre, el destino y los permisos.", untitledNote: "Sin título", untitledFolder: "Carpeta sin título", fileName: "Nombre", extensionKept: "La extensión del archivo se conserva automáticamente.", invalidName: "Introduce un nombre válido sin separadores de ruta ni caracteres especiales.", renameFailed: "No se pudo renombrar. Comprueba el nombre e inténtalo de nuevo.", cancel: "Cancelar",
  movedCount: "Se movieron {count} elementos a {folder}.", partialMove: "Se movieron {count} de {total} elementos. Los restantes no se movieron. Comprueba el destino e inténtalo de nuevo.",
  settingTitle: "Título de inicio", settingFolderIcon: "Icono de las tarjetas de carpeta", settingNavigationIcon: "Icono de navegación izquierda", iconName: "{name}", settingTitleDesc: "Título personalizado de la página de inicio. Déjalo vacío para usar el nombre predeterminado traducido.",
  lightColors: "Colores de portada en modo claro", darkColors: "Colores de portada en modo oscuro", folderCoverColors: "Colores de portada de carpetas", noteCoverColors: "Colores de portada de notas", gradientDesc: "Degradado de arriba a la izquierda hacia abajo a la derecha. Solo cambia el fondo, no la imagen.", gradientStart: "Color superior izquierdo", gradientEnd: "Color inferior derecho",
  cacheLocation: "Ubicación de caché (relativa a la bóveda)", cacheDesc: "Elimina solo miniaturas generadas de Canvas/PDF, nunca originales. Las visibles se regeneran cuando se necesitan. La caché no válida o huérfana se limpia automáticamente.", cacheFailed: "No se pudo vaciar la caché. Comprueba los permisos de la carpeta.",
  itemCount: "{count} elementos en esta carpeta", noMatches: "No hay elementos coincidentes en esta carpeta.", filterAria: "Filtrar la galería", sortAria: "Ordenar la galería", filterAll: "Todo", filterCanvas: "Canvas", filterNotes: "Notas", filterImages: "Imágenes", filterPdf: "PDF",
  sortModified: "Modificado recientemente", sortName: "Nombre", sortNameAsc: "Nombre de archivo (A–Z)", sortNameDesc: "Nombre de archivo (Z–A)", sortModifiedDesc: "Modificación (más reciente primero)", sortModifiedAsc: "Modificación (más antiguo primero)", sortCreatedDesc: "Creación (más reciente primero)", sortCreatedAsc: "Creación (más antiguo primero)", kindFolder: "Carpeta", kindCanvas: "Canvas", kindNote: "Nota", kindImage: "Imagen", kindPdf: "PDF",
  settingLanguage: "Idioma de la interfaz", settingLanguageDesc: "Elige el idioma de Visual Gallery.", settingCardWidth: "Ancho de tarjeta", settingCardWidthDesc: "Ajusta el ancho y la densidad de las tarjetas.", settingDefaultFilter: "Filtro predeterminado", settingDefaultFilterDesc: "Se aplica al abrir una nueva galería.", settingDefaultSort: "Orden predeterminado", settingDefaultSortDesc: "Se aplica al abrir una nueva galería.", settingMetadata: "Mostrar información secundaria", settingMetadataDesc: "Muestra el tipo de archivo y la fecha de modificación debajo del título.",
  commandOpen: "Abrir galería visual", commandRebuild: "Regenerar todas las miniaturas de Canvas", commandClear: "Vaciar caché de miniaturas", commandGenerate: "Generar miniatura de Canvas", thumbnailGenerated: "Miniatura de Canvas generada: {width}×{height}", thumbnailCached: "Miniatura de Canvas reutilizada: {width}×{height}", thumbnailWarnings: " ({count} advertencias de elementos)", thumbnailFailed: "Error al generar la miniatura de Canvas: {detail}", noCanvas: "Visual Gallery: no se encontraron archivos Canvas.", rebuilding: "Visual Gallery: regenerando {count} miniaturas de Canvas…", rebuilt: "Visual Gallery: se regeneraron {count} miniaturas de Canvas.", rebuildFailed: "Visual Gallery: {success} generadas; {failed} fallidas. Revisa la consola de desarrollo.", cacheCleared: "Se vació la caché de miniaturas de Visual Gallery.",
  dragUnavailable: "Esta versión de Obsidian no permite arrastrar archivos.", invalidTarget: "Una carpeta no puede moverse a sí misma ni a sus subcarpetas.", nameConflict: "El destino ya contiene un elemento con este nombre. No se movió nada.", movedTo: "Se movió {name} a {folder}.", moveFailed: "No se pudo mover. Comprueba el destino e inténtalo de nuevo.",
};

const FR: Dictionary = {
  sectionInterface: "Interface", sectionLayout: "Disposition des cartes", sectionBrowsing: "Navigation par défaut", sectionIcons: "Icônes", sectionCache: "Cache des miniatures",
  iconOriginal: "Icône de dossier d’origine", iconFolder: "Dossier", iconFolders: "Dossiers", iconArchive: "Archive", iconBox: "Boîte", iconLibrary: "Bibliothèque", iconBook: "Livre ouvert", iconHeart: "Dossier favori", iconCog: "Réglages du dossier", iconTree: "Arborescence", iconGrid: "Grille", iconGallery: "Galerie", iconImages: "Images", iconFilm: "Film", iconClapperboard: "Clap", iconPalette: "Palette", iconHome: "Accueil",
  viewTitle: "Galerie visuelle", gallery: "Galerie visuelle", rename: "Renommer", delete: "Supprimer", deleteFailed: "Suppression impossible. Vérifiez les permissions et réessayez.", showInFinder: "Afficher dans le Finder", showInSystem: "Afficher dans le gestionnaire de fichiers", revealFailed: "Impossible d’afficher cet élément dans le gestionnaire de fichiers.",
  newNote: "Nouvelle note", newFolder: "Nouveau dossier", create: "Créer", createFailed: "Création impossible. Vérifiez le nom, la destination et les permissions.", untitledNote: "Sans titre", untitledFolder: "Dossier sans titre", fileName: "Nom", extensionKept: "L’extension du fichier est conservée automatiquement.", invalidName: "Saisissez un nom valide sans séparateurs de chemin ni caractères spéciaux.", renameFailed: "Impossible de renommer. Vérifiez le nom et réessayez.", cancel: "Annuler",
  movedCount: "{count} éléments déplacés vers {folder}.", partialMove: "{count} éléments sur {total} déplacés. Les autres n’ont pas été déplacés. Vérifiez la destination et réessayez.",
  settingTitle: "Titre de l’accueil", settingFolderIcon: "Icône des cartes de dossier", settingNavigationIcon: "Icône de navigation à gauche", iconName: "{name}", settingTitleDesc: "Titre personnalisé de l’accueil. Laissez vide pour utiliser le nom traduit par défaut.", lightColors: "Couleurs de couverture en mode clair", darkColors: "Couleurs de couverture en mode sombre", folderCoverColors: "Couleurs des couvertures de dossier", noteCoverColors: "Couleurs des couvertures de note", gradientDesc: "Dégradé du coin supérieur gauche au coin inférieur droit. Modifie le fond, pas l’image.", gradientStart: "Couleur en haut à gauche", gradientEnd: "Couleur en bas à droite",
  cacheLocation: "Emplacement du cache (relatif au coffre)", cacheDesc: "Supprime uniquement les miniatures Canvas/PDF générées, jamais les originaux. Les miniatures visibles sont régénérées au besoin. Les entrées invalides ou orphelines sont nettoyées automatiquement.", cacheFailed: "Impossible de vider le cache. Vérifiez les permissions du dossier.", itemCount: "{count} éléments dans ce dossier", noMatches: "Aucun élément correspondant dans ce dossier.", filterAria: "Filtrer la galerie", sortAria: "Trier la galerie", filterAll: "Tout", filterCanvas: "Canvas", filterNotes: "Notes", filterImages: "Images", filterPdf: "PDF",
  sortModified: "Modifications récentes", sortName: "Nom", sortNameAsc: "Nom du fichier (A–Z)", sortNameDesc: "Nom du fichier (Z–A)", sortModifiedDesc: "Modification (du plus récent au plus ancien)", sortModifiedAsc: "Modification (du plus ancien au plus récent)", sortCreatedDesc: "Création (du plus récent au plus ancien)", sortCreatedAsc: "Création (du plus ancien au plus récent)", kindFolder: "Dossier", kindCanvas: "Canvas", kindNote: "Note", kindImage: "Image", kindPdf: "PDF",
  settingLanguage: "Langue de l’interface", settingLanguageDesc: "Choisissez la langue de Visual Gallery.", settingCardWidth: "Largeur des cartes", settingCardWidthDesc: "Ajustez la largeur et la densité des cartes.", settingDefaultFilter: "Filtre par défaut", settingDefaultFilterDesc: "Appliqué à l’ouverture d’une nouvelle galerie.", settingDefaultSort: "Tri par défaut", settingDefaultSortDesc: "Appliqué à l’ouverture d’une nouvelle galerie.", settingMetadata: "Afficher les informations secondaires", settingMetadataDesc: "Affiche le type de fichier et la date de modification sous le titre.",
  commandOpen: "Ouvrir la galerie visuelle", commandRebuild: "Régénérer toutes les miniatures Canvas", commandClear: "Vider le cache des miniatures", commandGenerate: "Générer une miniature Canvas", thumbnailGenerated: "Miniature Canvas générée : {width}×{height}", thumbnailCached: "Miniature Canvas réutilisée : {width}×{height}", thumbnailWarnings: " ({count} avertissements d’éléments)", thumbnailFailed: "Échec de la miniature Canvas : {detail}", noCanvas: "Visual Gallery : aucun fichier Canvas trouvé.", rebuilding: "Visual Gallery : régénération de {count} miniatures Canvas…", rebuilt: "Visual Gallery : {count} miniatures Canvas régénérées.", rebuildFailed: "Visual Gallery : {success} générées ; {failed} échecs. Consultez la console de développement.", cacheCleared: "Cache des miniatures de Visual Gallery vidé.",
  dragUnavailable: "Le glisser-déposer de fichiers est indisponible dans cette version d’Obsidian.", invalidTarget: "Un dossier ne peut pas être déplacé dans lui-même ou ses sous-dossiers.", nameConflict: "La destination contient déjà un élément de ce nom. Aucun élément n’a été déplacé.", movedTo: "{name} déplacé vers {folder}.", moveFailed: "Déplacement impossible. Vérifiez la destination et réessayez.",
};

const IT: Dictionary = {
  sectionInterface: "Interfaccia", sectionLayout: "Layout delle schede", sectionBrowsing: "Navigazione predefinita", sectionIcons: "Icone", sectionCache: "Cache delle miniature",
  iconOriginal: "Icona cartella originale", iconFolder: "Cartella", iconFolders: "Cartelle", iconArchive: "Archivio", iconBox: "Scatola", iconLibrary: "Biblioteca", iconBook: "Libro aperto", iconHeart: "Cartella preferita", iconCog: "Impostazioni cartella", iconTree: "Albero delle cartelle", iconGrid: "Griglia", iconGallery: "Galleria", iconImages: "Immagini", iconFilm: "Pellicola", iconClapperboard: "Ciak", iconPalette: "Tavolozza", iconHome: "Home",
  viewTitle: "Galleria visuale", gallery: "Galleria visuale", rename: "Rinomina", delete: "Elimina", deleteFailed: "Impossibile eliminare. Controlla i permessi e riprova.", showInFinder: "Mostra nel Finder", showInSystem: "Mostra nel gestore file", revealFailed: "Impossibile mostrare questo elemento nel gestore file.", newNote: "Nuova nota", newFolder: "Nuova cartella", create: "Crea", createFailed: "Impossibile creare. Controlla nome, destinazione e permessi.", untitledNote: "Senza titolo", untitledFolder: "Cartella senza titolo", fileName: "Nome", extensionKept: "L’estensione del file viene mantenuta automaticamente.", invalidName: "Inserisci un nome valido senza separatori di percorso o caratteri speciali.", renameFailed: "Impossibile rinominare. Controlla il nome e riprova.", cancel: "Annulla",
  movedCount: "Spostati {count} elementi in {folder}.", partialMove: "Spostati {count} elementi su {total}. Gli altri non sono stati spostati. Controlla la destinazione e riprova.", settingTitle: "Titolo della pagina iniziale", settingFolderIcon: "Icona delle schede cartella", settingNavigationIcon: "Icona di navigazione a sinistra", iconName: "{name}", settingTitleDesc: "Titolo personalizzato della galleria. Lascia vuoto per usare il nome tradotto predefinito.",
  lightColors: "Colori copertina in modalità chiara", darkColors: "Colori copertina in modalità scura", folderCoverColors: "Colori copertina delle cartelle", noteCoverColors: "Colori copertina delle note", gradientDesc: "Sfumatura dall’angolo in alto a sinistra a quello in basso a destra. Cambia lo sfondo, non l’immagine.", gradientStart: "Colore in alto a sinistra", gradientEnd: "Colore in basso a destra", cacheLocation: "Posizione cache (relativa al vault)", cacheDesc: "Elimina solo le miniature Canvas/PDF generate, non gli originali. Quelle visibili vengono rigenerate quando necessario. La cache non valida o orfana viene pulita automaticamente.", cacheFailed: "Impossibile svuotare la cache. Controlla i permessi della cartella.",
  itemCount: "{count} elementi in questa cartella", noMatches: "Nessun elemento corrispondente in questa cartella.", filterAria: "Filtra la galleria", sortAria: "Ordina la galleria", filterAll: "Tutti", filterCanvas: "Canvas", filterNotes: "Note", filterImages: "Immagini", filterPdf: "PDF", sortModified: "Modificati di recente", sortName: "Nome", sortNameAsc: "Nome del file (A–Z)", sortNameDesc: "Nome del file (Z–A)", sortModifiedDesc: "Modifica (dal più recente)", sortModifiedAsc: "Modifica (dal meno recente)", sortCreatedDesc: "Creazione (dal più recente)", sortCreatedAsc: "Creazione (dal meno recente)", kindFolder: "Cartella", kindCanvas: "Canvas", kindNote: "Nota", kindImage: "Immagine", kindPdf: "PDF",
  settingLanguage: "Lingua dell’interfaccia", settingLanguageDesc: "Scegli la lingua di Visual Gallery.", settingCardWidth: "Larghezza delle schede", settingCardWidthDesc: "Regola larghezza e densità delle schede.", settingDefaultFilter: "Filtro predefinito", settingDefaultFilterDesc: "Applicato all’apertura di una nuova galleria.", settingDefaultSort: "Ordinamento predefinito", settingDefaultSortDesc: "Applicato all’apertura di una nuova galleria.", settingMetadata: "Mostra informazioni secondarie", settingMetadataDesc: "Mostra tipo di file e data di modifica sotto il titolo.", commandOpen: "Apri galleria visuale", commandRebuild: "Rigenera tutte le miniature Canvas", commandClear: "Svuota cache delle miniature", commandGenerate: "Genera miniatura Canvas", thumbnailGenerated: "Miniatura Canvas generata: {width}×{height}", thumbnailCached: "Miniatura Canvas riutilizzata: {width}×{height}", thumbnailWarnings: " ({count} avvisi sugli elementi)", thumbnailFailed: "Miniatura Canvas non riuscita: {detail}", noCanvas: "Visual Gallery: nessun file Canvas trovato.", rebuilding: "Visual Gallery: rigenerazione di {count} miniature Canvas…", rebuilt: "Visual Gallery: rigenerate {count} miniature Canvas.", rebuildFailed: "Visual Gallery: {success} generate; {failed} non riuscite. Controlla la console di sviluppo.", cacheCleared: "Cache delle miniature di Visual Gallery svuotata.",
  dragUnavailable: "Il trascinamento dei file non è disponibile in questa versione di Obsidian.", invalidTarget: "Non puoi spostare una cartella dentro sé stessa o le sue sottocartelle.", nameConflict: "La destinazione contiene già un elemento con questo nome. Nulla è stato spostato.", movedTo: "Spostato {name} in {folder}.", moveFailed: "Impossibile spostare. Controlla la destinazione e riprova.",
};

export const EXTRA_TRANSLATIONS: Record<Exclude<UiLanguage, "en" | "zh-TW" | "zh-CN" | "ja">, Dictionary> = {
  de: DE, es: ES, fr: FR, it: IT, "pt-BR": PT_BR, ko: KO, ru: RU, uk: UK,
  nl: NL, pl: PL, tr: TR, id: ID, vi: VI, th: TH,
};
